// This is an Autogenerated code, don't touch!

namespace KrillAudio.Krilloud
{
	public class KL
	{
		public class Tags
		{
			/// <summary>
			/// Tag: NewTag
			/// 2D
			/// </summary>
			[System.Obsolete("Cache")]
			public const string NewTag = "NewTag";

			/// <summary>
			/// Tag: test
			/// 2D
			/// </summary>
			[System.Obsolete("Placeholder")]
			public const string test = "test";

		}

		public class Variables
		{
		}

		public class Channels
		{
		}
	}
}
