// This is an Autogenerated code, don't touch!

namespace KrillAudio.Krilloud
{
	public class KL
	{
		public class Tags
		{
			/// <summary>
			/// Tag: bg_sfx
			/// 2D
			/// </summary>
			[System.Obsolete("Placeholder")]
			public const string bg_sfx = "bg_sfx";

			/// <summary>
			/// Tag: counter_sfx
			/// 2D
			/// </summary>
			public const string counter_sfx = "counter_sfx";

			/// <summary>
			/// Tag: fail_sfx
			/// 2D
			/// </summary>
			public const string fail_sfx = "fail_sfx";

			/// <summary>
			/// Tag: final_ost
			/// 2D
			/// </summary>
			public const string final_ost = "final_ost";

			/// <summary>
			/// Tag: game_ost
			/// 2D
			/// </summary>
			[System.Obsolete("Placeholder")]
			public const string game_ost = "game_ost";

			/// <summary>
			/// Tag: hover_button
			/// 2D
			/// </summary>
			public const string hover_button = "hover_button";

			/// <summary>
			/// Tag: inicio_sfx
			/// 2D
			/// </summary>
			public const string inicio_sfx = "inicio_sfx";

			/// <summary>
			/// Tag: limits_sfx
			/// 2D
			/// </summary>
			public const string limits_sfx = "limits_sfx";

			/// <summary>
			/// Tag: main_ost
			/// 2D
			/// </summary>
			public const string main_ost = "main_ost";

			/// <summary>
			/// Tag: multiplier_sfx
			/// 2D
			/// </summary>
			public const string multiplier_sfx = "multiplier_sfx";

			/// <summary>
			/// Tag: music
			/// 2D
			/// </summary>
			public const string music = "music";

			/// <summary>
			/// Tag: perfect_sfx
			/// 2D
			/// </summary>
			public const string perfect_sfx = "perfect_sfx";

			/// <summary>
			/// Tag: press_button
			/// 2D
			/// </summary>
			public const string press_button = "press_button";

			/// <summary>
			/// Tag: touch_sfx
			/// 2D
			/// </summary>
			public const string touch_sfx = "touch_sfx";

		}

		public class Variables
		{
			/// <summary>
			/// Variable: layer1
			/// Range: [0 - 1]
			/// Type: Local
			/// </summary>
			public const string layer1 = "layer1";

			/// <summary>
			/// Variable: layer2
			/// Range: [0 - 1]
			/// Type: Local
			/// </summary>
			public const string layer2 = "layer2";

			/// <summary>
			/// Variable: layer3
			/// Range: [0 - 1]
			/// Type: Local
			/// </summary>
			public const string layer3 = "layer3";

			/// <summary>
			/// Variable: layers
			/// Range: [0 - 2]
			/// Type: Local
			/// </summary>
			public const string layers = "layers";

			/// <summary>
			/// Variable: MusicGeneral
			/// Range: [0 - 0]
			/// Type: Local
			/// </summary>
			[System.Obsolete("Placeholder")]
			public const string MusicGeneral = "MusicGeneral";

			/// <summary>
			/// Variable: SFXGeneral
			/// Range: [0 - 0]
			/// Type: Local
			/// </summary>
			[System.Obsolete("Placeholder")]
			public const string SFXGeneral = "SFXGeneral";

			/// <summary>
			/// Variable: VolumeGeneral
			/// Range: [0 - 0]
			/// Type: Local
			/// </summary>
			[System.Obsolete("Placeholder")]
			public const string VolumeGeneral = "VolumeGeneral";

		}

		public class Channels
		{
			public const string Master = "Master";

		}
	}
}
